### ISSUE TITLE
Building from source error with CUDA & eigen3

### ISSUE THREAD

**Issue by devshank3** [neka-nat/cupoch#1]
Hello @neka-nat,

A huge thanks for Cupoch

But im facing issue while building from source 

system config

Nvidia geforce 1650
cuda toolkit 10.2
ubuntu 19.10
inbuilt Eigen : eigen 3.3.7

I tried with both eigen3 3rdparty and inbuilt version using 
`cmake -DBUILD_EIGEN3=OFF`
and 
`cmake -DBUILD_EIGEN3=ON`

the make `make install-pip-package -j`  is getting killed 

few error snippets are 

`/home/shankar/3D projects/cupoch/cupoch/src/cupoch/geometry/boundingvolume.cu(26): error: identifier "Eigen::MatrixBase< ::Eigen::Matrix<float, (int)3, (int)3, (int)0, (int)3, (int)3> > ::determinant const" is undefined in device code
`

`36 errors detected in the compilation of "/tmp/tmpxft_00007184_00000000-6_boundingvolume.cpp1.ii".
CMake Error at cupoch_geometry_generated_boundingvolume.cu.o.cmake:280 (message):
  Error generating file /home/shankar/3D
  projects/cupoch/cupoch/build/src/cupoch/geometry/CMakeFiles/cupoch_geometry.dir//./cupoch_geometry_generated_boundingvolume.cu.o
`

`make[1]: *** [CMakeFiles/Makefile2:755: src/cupoch/geometry/CMakeFiles/cupoch_geometry.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by neka-nat** [comment]
Hi @devshank3 ,

Thank you for reporting.
Compilation may not pass with version 3.3.7 of eigen.
When using third_party, the version should be 3.3.90.
Please try the following:
* Remove CMakeCache.txt
* Remove eigen3 installed on the system

**Comment by devshank3** [comment]
Now tried with  eigen3 installed was 3.3.90 

still got killed 

![Screenshot from 2020-02-23 19-45-10](https://user-images.githubusercontent.com/52159502/75113582-27f8ca80-5675-11ea-8aa2-48c501cacac8.png)

**Comment by neka-nat** [comment]
"Killed" messages are like someone has sent Kill signals.
Suspect Kill signal from a system such as OOMKiller.

**Comment by devshank3** [comment]
Sure i will try and let u know for  **building from source**

Mean while i installed Cupoch in my system via pip 

but few errors 

![Screenshot from 2020-02-23 21-55-38](https://user-images.githubusercontent.com/52159502/75116066-7369a380-568a-11ea-9c26-aa6ea8184ff4.png)
![Screenshot from 2020-02-23 22-07-50](https://user-images.githubusercontent.com/52159502/75116074-85e3dd00-568a-11ea-93be-83d5a9f111db.png)
![Screenshot from 2020-02-23 22-20-23](https://user-images.githubusercontent.com/52159502/75116088-b592e500-568a-11ea-8c52-2d83e9cfab4a.png)

mainly cuda mem alloc

**Comment by neka-nat** [comment]
I have updated the version of the pip package (v0.0.3).
Please install it again and try it.

**Comment by devshank3** [comment]
works great thank you

**Comment by neka-nat** [comment]
Thank you!
It seems that there was still a fatal defect.
I have upgraded the version to 0.0.4, so please try again.
