### ISSUE TITLE
Is it possible to use Open3D and Cupoch together?

### ISSUE THREAD

**Issue by 1939938853** [neka-nat/cupoch#10]
Hello, 

I tried to use Open3d and Cupoch together side-by-side for comparison. But got something redefined error. Here is my code

`
 auto pcd_gpu = cupoch::io::CreatePointCloudFromFile("pcd1.pcd");
 auto pcd = open3d::io::CreatePointCloudFromFile("pcd1.pcd");
`

Here is the error messages

![image](https://user-images.githubusercontent.com/59957922/88474787-3865e780-cf2a-11ea-8410-db14683d51bf.png)

Anyway to solve this issue?

Thank you!

**Comment by neka-nat** [comment]
Hi @1939938853 ,

Thank you for the reporting.
It sounds like a problem with fmt and tinyobjloader libraries.
I think the following issues are related to the tinyobjeloader one.
https://github.com/tinyobjloader/tinyobjloader/issues/171
I didn't find any related issues with fmt.

**Comment by 1939938853** [comment]
It looks that we need to manually modify the header files of both fmt and tinyobjloader.

By the way, what is the suggestion for best covert Open3D 3D data to Cupoch and vice versa. static_cast or via the eigenvector?

Thank you!

**Comment by neka-nat** [comment]
The open3d point cloud is a std::vector.
By contrast, cupoch is a thrust::device_vector.
It can be copied by the assignment operator.
https://stackoverflow.com/questions/43982841/how-to-copy-host-vector-to-device-vector-by-thrust

```
open3d::geometry::PointCloud pcd_cpu;
// Initialize pcd_cpu...
cupoch::geometry::PointCloud pcd_gpu;
pcd_gpu.points_ = pcd_cpu.points_;
```

**Comment by 1939938853** [comment]
Want to use Cupoch together with Open3D but facing the problem

Cupoch use CMAKE_CXX_FLAG MD/MDd while Open3D use MT/MTd. Tried several times to change Cupoch cmake option to MD in building Cupoch, but without success -- no change happend.
