### ISSUE TITLE
Outlier Removal Not working

### ISSUE THREAD

**Issue by nithinpanand** [neka-nat/cupoch#101]
I have an issue with the outlier removing code. I am getting the following output when testing with my .ply file and also the .pcd file in the example (https://github.com/neka-nat/cupoch/blob/master/examples/python/advanced/pointcloud_outlier_removal.py). I used both Statistical oulier removal and Radius oulier removal and both have the same issue. 
 
```
 Unable to convert function return value to a Python type! The signature was
(self: cupoch.cupoch.geometry.PointCloud, nb_neighbors: int, std_ratio: float) -> 
Tuple[cupoch.cupoch.geometry.PointCloud, cupoch::wrapper::device_vector_wrapper<unsigned __int64>]
```

Please have a look..

**Comment by neka-nat** [comment]
Hi,
Thanks for the report!
It has been fixed in the latest master.
