### ISSUE TITLE
speed performace VS open3d

### ISSUE THREAD

**Issue by MonsieurMiku** [neka-nat/cupoch#117]
hello authors, cupoch is a nice jobs. Now I test the performance of point clouds processing in a small lidar datasets compared with Open3d.

There are not obvious speed difference in my test data which may be small. 

The input is the lidar points (3500, 3), and there are my test result.
[open3d]     method              time
o3d, np_to_03d_convert: 3.528594970703125e-05
o3d, voxel_down_sample: 0.0007774829864501953
o3d, remove_radius_outlier: 0.0023055076599121094
sklearn.cluster, dbscan: 0.013736963272094727
o3d, o3d -> numpy: 1.1205673217773438e-05

[cupoch]        method              time
cupoch, np_to_cph_convert: 0.0006957054138183594
cupoch, voxel_down_sample: 0.0006439685821533203
cupoch, remove_radius_outlier: 0.0038330554962158203
cupoch, cluster_dbscan: 0.17143726348876953
cupoch, cupoch -> numpy: 0.0008497238159179688

my test function using python:

def speed_test(lidar_points):
    lidar_points = np.round(lidar_points, 2)
    print('>>>>>>>>>>>>>>>>> start test <<<<<<<<<<<<<<<<<<')
    # ----------- open3d -----------
    lidar_points_o3d = lidar_points.copy()
    # numpy to open3d
    s = time.time()
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(lidar_points_o3d)
    print('o3d, np_to_03d_convert:', time.time() - s)
    s = time.time()
    voxel_grid = pcd.voxel_down_sample(voxel_size=0.25)
    print('o3d, voxel_down_sample:', time.time() - s)
    s = time.time()
    _, index = pcd.remove_radius_outlier(nb_points=15, radius=1.5)
    print('o3d, remove_radius_outlier:', time.time() - s)
    s = time.time()
    _, radar_dbscan_kind = dbscan(lidar_points,
                                  eps=g.eps_radar_multiframes,
                                  min_samples=g.min_samples_radar_multiframes,
                                  algorithm='ball_tree',
                                  leaf_size=10)
    # open3d to numpy
    s = time.time()
    points = np.asarray(pcd.points)
    print('o3d, o3d -> numpy:', time.time() - s)
    
    # ----------- cupoch -----------
    lidar_points_gpu = lidar_points.copy()
    # numpy -> cupoch
    s = time.time()
    pc_gpu = cph.geometry.PointCloud()
    pc_gpu.points = cph.utility.Vector3fVector(lidar_points_gpu)
    print('cupoch, np_to_cph_convert:', time.time() - s)
    s = time.time()
    res = pc_gpu.voxel_down_sample(voxel_size=0.25)
    print('cupoch, voxel_down_sample:', time.time() - s)
    s = time.time()
    _, index = pc_gpu.remove_radius_outlier(nb_points=15, radius=1.5)
    print('cupoch, remove_radius_outlier:', time.time() - s)
    s = time.time()
    res = pc_gpu.cluster_dbscan(eps=g.eps_radar_multiframes, min_points=g.min_samples_radar_multiframes)
    print('cupoch, cluster_dbscan:', time.time() - s)
    # cupoch -> numpy
    s = time.time()
    temp = np.asarray(pc_gpu.points.cpu())
    print(temp.shape)
    print('cupoch, cupoch -> numpy:', time.time() - s)

**Comment by neka-nat** [comment]
As you say, a calculation with a point cloud of 3500 points might not make a difference.
I think a point cloud of 100,000 points or more would work.
