### ISSUE TITLE
Error: OS call failed or operation not supported on this OS phong_shader.cu:330

### ISSUE THREAD

**Issue by ambitious-octopus** [neka-nat/cupoch#118]
i am trying to use this script (https://github.com/neka-nat/cupoch/blob/master/examples/python/robotics/collision_voxelgrid.py) on pop-os 22.04 unfortunately i get this error.  

```
collision::CollisionResult with 120 collisions.
Error: OS call failed or operation not supported on this OS	phong_shader.cu:330
```

```bash
>> uname -a
Linux pop-os 6.2.6-76060206-generic x86_64 GNU/Linux
```

**Comment by neka-nat** [comment]
Thanks for the report!
You can try the following
https://forums.developer.nvidia.com/t/cudaerrorunknown-cudagraphicsglregisterbuffer/64406/10

```sh
cd examples/python/basic
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia python visualization.py
```
