### ISSUE TITLE
cupoch is slower than open3d-cpu and open3d-gpu

### ISSUE THREAD

**Issue by mcmingchang** [neka-nat/cupoch#127]
PointCloud with 115711 points.
o3d version 0.18.0
cupoch version  0.2.10.0

**Comment by mcmingchang** [comment]
windows 11   cuda 11.8   python3.11

**Comment by neka-nat** [comment]
Hi,
Thanks for the report!
If you can provide the actual code, I may be able to find the cause of the slowdown.
