### ISSUE TITLE
install on Jetson Xavier Agx

### ISSUE THREAD

**Issue by Fred3D-tech** [neka-nat/cupoch#14]
Great project !
I would like to test it on a Xavier Agx .. I was able to install cupoch but I can't use Jetcard..
then, when I try your examples, I have no error but I don't get any output...
What can I do ?

**Comment by neka-nat** [comment]
Hi @Fred3D-tech ,

Thanks for trying it out on jetson.
I would like to know the details of the issue.
Which example is it?
What exactly do you mean by "don't get any output..."?
