### ISSUE TITLE
Add matcaps rendering to cupoch

### ISSUE THREAD

**Issue by 1939938853** [neka-nat/cupoch#25]
Hello, 

Is this [matcaps](http://polyscope.run/features/materials/) rendering interesting to add to cupoch?

I think the biggest advantage for [matcaps rendering](https://www.google.com/search?source=hp&ei=rTaYX5T0Gc2LlwSQ3pagAQ&q=matcaps+rendering&oq=matcaps+rendering&gs_lcp=CgZwc3ktYWIQAzoFCAAQsQM6CAgAELEDEIMBOggILhCxAxCDAToCCAA6BQguELEDOgQIABAKOgQILhAKOgQIABAeOgYIABAKEB46BQghEKABOgYIABAWEB46CAgAEBYQChAeOggIIRAWEB0QHlD2I1jldmCie2gCcAB4AIABgwKIAdcKkgEGMTYuMS4xmAEAoAEBqgEHZ3dzLXdperABAA&sclient=psy-ab&ved=0ahUKEwjU_r7ChdXsAhXNxYUKHRCvBRQQ4dUDCAY&uact=5) is it is "cheap" to achieve and it looks very attractive!

Thank you!

**Comment by neka-nat** [comment]
Sounds good!

**Comment by 1939938853** [comment]
[Here](http://www.beautybuddyapp.com/examples/matcap.html) is also a good matcaps implementation example.
