### ISSUE TITLE
PointCloud loads slower for GPU than CPU

### ISSUE THREAD

**Issue by maxarady** [neka-nat/cupoch#26]
First, I wanted to say this is a great library!

During testing, I've noticed the following:

**read_point_cloud (CPU) [sec]: 0.048947811126708984**
PointCloud with 196133 points.
**read_point_cloud (GPU) [sec]: 0.594552755355835**
geometry::PointCloud with 196133 points.
transform (CPU) [sec]: 0.0018947124481201172
transform (GPU) [sec]: 0.0005991458892822266
estimate_normals (CPU) [sec]: 0.8370163440704346
estimate_normals (GPU) [sec]: 0.13143420219421387
voxel_down_sample (CPU) [sec]: 0.08861064910888672
voxel_down_sample (GPU) [sec]: 0.0065348148345947266
remove_radius_outlier (CPU) [sec]: 7.660656690597534
remove_radius_outlier (GPU) [sec]: 0.05325913429260254
remove_statistical_outlier (CPU) [sec]: 0.6584312915802002
remove_statistical_outlier (GPU) [sec]: 0.07167720794677734
registration_icp (CPU) [sec]: 10.772068977355957
registration_icp (GPU) [sec]: 0.10024285316467285
cluster_dbscan (CPU) [sec]: 1.0398595333099365
cluster_dbscan (GPU) [sec]: 0.3085062503814697

It seems the read_point_cloud functionality, is 1 order of magnitude larger for GPU, which seems to effectively bottleneck some of the value of the GPU efficiencies derived from things like FastGlobalRegistration, which is markedly faster than ICP. Does this mean that cupoch will always perform slower on FastGlobalRegistration a compared to ICP just from the overhead of I/O to VRAM?

I also tested this in a series of load and FastGlobalRegistration iterations, with the following result: 75% of the time was spend loading and unloading to VRAM, while 25% of the time was actually on FastGlobalRegistration.

This is being tested on a GTX Titan 6GB, which is listed here: https://www.geforce.com/hardware/desktop-gpus/geforce-gtx-titan/specifications

**Comment by neka-nat** [comment]
Hi,

Thank you.
As you say, the transfer to VRAM is generally the part with the most overhead.
Using Jetson's Unified memory might help with that, but I haven't tried it yet.
