### ISSUE TITLE
Image conversion between OpenCV and cupoch

### ISSUE THREAD

**Issue by godfather1402** [neka-nat/cupoch#29]
Hi,
Thank you for great work.
I would like to convert OpenCV image types (CV_8C3, CV_16UC1, CV_32FC1, ...) to cupoch image. Do you know the best way to upload and download to OpenCV image. 
Thank you

**Comment by neka-nat** [comment]
Hi,
I made an example for opencv.
Please refer to it.
https://github.com/neka-nat/cupoch/blob/master/examples/python/basic/opencv_interop.py
