### ISSUE TITLE
realsense_kinfuを実行する事が出来ません

### ISSUE THREAD

**Issue by Kyosuke45628** [neka-nat/cupoch#31]
はじめまして．
realsenseでkinectfusionを実行したいのですがubuntuにて実行した場合下記のようなエラーが出てしまいます．
何か対策案はありますでしょうか？
エラー文が何も出ないのでprintを用いて文章が表示されるのかという事を各行で行った際に84行目のコードが実行されないようです．
infu = cph.kinfu.Pipeline(intrinsic, cph.kinfu.KinfuParameters())

[環境]
・ubuntu18.04
・windows visual studio
・cuda-10

ubuntuのネイティブで実装した際には下記のエラーが発生してしまいました．

Traceback (most recent call last):
  File "benchmarks.py", line 4, in <module>
    import cupoch as cph
  File "/home/nvidia/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cupoch/__init__.py", line 1, in <module>
    from .cupoch import * # py2 py3 compatible
ImportError: CUDA error at: /home/runner/work/cupoch/cupoch/third_party/rmm/include/rmm/mr/device/per_device_resource.hpp:134: cudaErrorNoDevice no CUDA-capable device is detected

**Comment by neka-nat** [comment]
@Kyosuke45628 

ご質問頂きありがとうございます。
エラーメッセージの内容を見ますと、CUDAで認識できるデバイスが見つからなかったようです。
まずは使用しているGPUとnvidiaドライバの動作をご確認いただければと思います。
