### ISSUE TITLE
Is there any plan to port cupoch for ROS2?

### ISSUE THREAD

**Issue by ldg810** [neka-nat/cupoch#40]
Hi, I am interesting with cupoch to use the library in Jetson Nano.

Do you have any plan to port the cupoch for ROS2 environment?

Thank you.

**Comment by neka-nat** [comment]
Hi @ldg810 ,
Thanks for the question!
I've added an example for ros2.
This example receives pointcloud2 from [the realsense node](https://github.com/intel/ros2_intel_realsense/tree/refactor).
It works with the latest master.
https://github.com/neka-nat/cupoch/blob/master/examples/python/ros2/pointcloud2_msg.py

**Comment by ldg810** [comment]
> Hi @ldg810 ,
> Thanks for the question!
> I've added an example for ros2.
> This example receives pointcloud2 from [the realsense node](https://github.com/intel/ros2_intel_realsense/tree/refactor).
> It works with the latest master.
> https://github.com/neka-nat/cupoch/blob/master/examples/python/ros2/pointcloud2_msg.py

Thank you very much!

**Comment by ZhenshengLee** [comment]
@ldg810 Hi, you can use this repo https://github.com/ZhenshengLee/perception_cupoch/tree/foxy for cupoch + ros2 development, feel free to create issues.
