### ISSUE TITLE
util_type.cuh line 891 issue

### ISSUE THREAD

**Issue by 1939938853** [neka-nat/cupoch#41]
Hello,

I got cupoch compiling issue as shown on the following pic. I'm using

cupoch v0.1.8, VS2019, cuda 10.2

thank you!

![image](https://user-images.githubusercontent.com/59957922/108101242-3eb6df00-7087-11eb-8f65-0232af4445da.png)

**Comment by neka-nat** [comment]
Thank you for reporting!
On windows, cupoch can not be currently compiled with cuda10.2, so please use cuda11.0.

**Comment by 1939938853** [comment]
OK. cuda 11.0 works with cupoch compiling on WIndows
