### ISSUE TITLE
std::max std::min

### ISSUE THREAD

**Issue by 1939938853** [neka-nat/cupoch#44]
![image](https://user-images.githubusercontent.com/59957922/108541390-b16fc680-72e2-11eb-8d35-9bbb8cef4ccd.png)

**Comment by 1939938853** [comment]
I'm using vs2019 cupoch 0.1.8

**Comment by neka-nat** [comment]
Thank you for the reporting!
On github action, it compiles with windows, vs2019 and cuda11.0, so I think other environment settings are different.
https://github.com/neka-nat/cupoch/actions/runs/571800245
Can you please check the github action configuration?
