### ISSUE TITLE
many link errors on windows with vs2019

### ISSUE THREAD

**Issue by 1939938853** [neka-nat/cupoch#46]
![image](https://user-images.githubusercontent.com/59957922/108548724-89856080-72ec-11eb-9e31-8258436748e2.png)

**Comment by neka-nat** [comment]
Thank you for the reporting!
On github action, it compiles with windows, vs2019 and cuda11.0, so I think other environment settings are different.
https://github.com/neka-nat/cupoch/actions/runs/571800245
Can you please check the github action configuration?
