### ISSUE TITLE
In windows use cupoch lib

### ISSUE THREAD

**Issue by xiaopeige** [neka-nat/cupoch#49]
I want use cupoch library in windows，like open3d，#include <Open3D/Open3D.h>, but there is a problem when using cupoch in winndows, is it supported now?

**Comment by neka-nat** [comment]
Thank you for the question!
What kind of problem is it?

**Comment by xiaopeige** [comment]
> Thank you for the question!
> What kind of problem is it?

Unable to reference third-party libraries, cupoch.lib cannot be used, I want to know if you have tested and used cupoch.lib on windows?

**Comment by neka-nat** [comment]
I have confirmed that it works on windows, but there have been some problems reported. #30

**Comment by xiaopeige** [comment]
> I have confirmed that it works on windows, but there have been some problems reported. #30

Yes, currently I can successfully generate the include folder and lib folder, but are there any examples of how to reference these two folders?

**Comment by neka-nat** [comment]
The examples cmake will be helpful.
https://github.com/neka-nat/cupoch/blob/master/examples/cpp/CMakeLists.txt
