### ISSUE TITLE
Is there anyway to do multiple ICPs at once.

### ISSUE THREAD

**Issue by KalraA** [neka-nat/cupoch#50]
Hello @neka-nat,

This is an incredible project. Thank you so much! I have a quesiton:

I have N pairs of point clouds and I have to do ICP between each pair. I have 2 GPUs and I'm not sure if there is any good way of running simultaneous registration. I tried using python multprocessing but it actually slows it down by 3x rather than speeding it up. Any thoughts are welcome!

**Comment by xiaopeige** [comment]
> Hello @neka-nat,
> 
> This is an incredible project. Thank you so much! I have a quesiton:
> 
> I have N pairs of point clouds and I have to do ICP between each pair. I have 2 GPUs and I'm not sure if there is any good way of running simultaneous registration. I tried using python multprocessing but it actually slows it down by 3x rather than speeding it up. Any thoughts are welcome!

Excuse me, are you going to perform loop detection?

**Comment by KalraA** [comment]
No, I'm trying to perform multiple object pose estimation. I have a point cloud of a scene with many objects, and a point cloud of each object. I'm trying to register each object point cloud to the corresponding part of the scene. I have an initial estimate for each object, and want to refine using ICP. 

Does this help?

**Comment by neka-nat** [comment]
Hi,

Thank you for the question!
In the current implementation, the only way to do this is to execute them one by one in order.
In the future, it will be possible to speed up the process if ICP can be executed in multiple cuda streams.
In order to do so, it is necessary to implement ICP with specifying the cuda stream.

**Comment by KalraA** [comment]
Hi @neka-nat, 

Thank you for your response. I am interested to try to implement this. Could you give me some pointers as to how you would go about doing it?

**Comment by neka-nat** [comment]
The following site is helpful for handling CUDA stream.
Also, OpenCV provides stream interface in the functions, and parallelization is possible by explicitly specifying stream.
https://developer.download.nvidia.com/CUDA/training/StreamsAndConcurrencyWebinar.pdf
https://stackoverflow.com/questions/17842827/how-to-use-gpustream-in-opencv

**Comment by tomy807** [comment]
> No, I'm trying to perform multiple object pose estimation. I have a point cloud of a scene with many objects, and a point cloud of each object. I'm trying to register each object point cloud to the corresponding part of the scene. I have an initial estimate for each object, and want to refine using ICP.
> 
> Does this help?

Hello, I’m also trying to solve the problem you were working on. May I ask how you resolved it? Although it has been a while, I’m leaving a comment hoping to get some advice.

**Comment by tomy807** [comment]
> No, I'm trying to perform multiple object pose estimation. I have a point cloud of a scene with many objects, and a point cloud of each object. I'm trying to register each object point cloud to the corresponding part of the scene. I have an initial estimate for each object, and want to refine using ICP.
> 
> Does this help?

Hi! @KalraA 
Hello, I’m also trying to solve the problem you were working on. 
May I ask how you resolved it? 
Although it has been a while, I’m leaving a comment hoping to get some advice.
