### ISSUE TITLE
 specify the GPU

### ISSUE THREAD

**Issue by gq124** [neka-nat/cupoch#53]
Hi, How to specify the GPU  when running a demo program

**Comment by neka-nat** [comment]
Hi,
How about using the CUDA_VISIBLE_DEVICES environment variable?

**Comment by gq124** [comment]
Thank you for your reply. I know running a demo program on linux  can use the CUDA_VISIBLE_DEVICES environment variable to specify the GPU. But ,how to specify the GPU device when running a  cupoch demo  program in vs2019, Do you have any good ideas?

**Comment by KalraA** [comment]
You can set it from python itself.
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
If you put this as the very first lines of python your demo runs it should be the same.
