### ISSUE TITLE
sample_points_uniformly function becomes slower in cupoch

### ISSUE THREAD

**Issue by kaixin-bai** [neka-nat/cupoch#6]
I test sample_points_uniformly function in both open3d and cupoch. cupoch is slower than open3d. In which kind of situations gpu could make the calculation faster than cpu?

For 50000 points:
```
cupoch: 0.04s
open3d: 0.002s
```
For 5000000 points:
```
cupoch: 3.5s
open3d: 0.2s
```

**Comment by neka-nat** [comment]
Hi @kaixin-bai ,

Thanks for your reporting!
I pushed a performance-improved `sample_points_uniformly` function in the master branch.
Please try it out.

**Comment by neka-nat** [comment]
I also update pypi package.
Please update the package and try it.

```
pip install -U cupoch
```
