### ISSUE TITLE
Occupancy grid understanding 

### ISSUE THREAD

**Issue by aditdoshi333** [neka-nat/cupoch#65]
Thank you for sharing such amazing work. 

For a project, I am using L515 and I wanted to detect obstacles coming in the path of the bot (L515 is mounted on a bot). I was thinking to use occupancy grid example by some way but I am not able to understand the output of occupancy grid. Can you please throw some light on the output of the occupancy grid?

If not occupancy grid can you suggest some functionality from your library I can use to proceed with such a problem.

Thanks a lot.

**Comment by neka-nat** [comment]
Hi,
Thank you for asking!
The OccupancyGrid class has a dense grid that contains information on whether it is an obstacle or not.
If it is to be used for obstacle avoidance, the `voxels` property can be used to get a list of detected voxels.
The voxels contain the occupancy log liklihood, and if it is greater than `oc_prob_thres_log`, then it is an obstacle cell.
