### ISSUE TITLE
Real-time 3D reconstruction

### ISSUE THREAD

**Issue by xiaopeige** [neka-nat/cupoch#66]
I have a project. The requirement is to achieve real-time 3D reconstruction (30 frames). The data I can get here is a continuous point cloud. I know that I need to complete the matching between two point clouds using FGR. However, with the appearance of accumulated errors, loopback detection and loopback optimization are required. Do you have any suggestions if I use Cupoch to implement this project?
Thank you!

**Comment by neka-nat** [comment]
Hi @xiaopeige ,
Graph optimization is not implemented in cupoch.
Probably, graph optimization is not so compatible with parallelization by CUDA.
So, you need to use other libraries such as g2o or open3d for that part.
