### ISSUE TITLE
[Release request] Provice cupoch-fat-source.tar.gz archive that contains the cupoch Source and all git submodules.

### ISSUE THREAD

**Issue by ZhenshengLee** [neka-nat/cupoch#68]
Hi, @neka-nat 

Could you add a fat-source tar archive with all git submodules in next release, which can save a lot of time for compiling in embeded devices?

It would be like this page [eCAL 5.9.0 release page](https://github.com/continental/ecal/releases)

Many thanks.

**Comment by neka-nat** [comment]
Thanks!
I'll deal with it!

**Comment by neka-nat** [comment]
I uploaded.
https://github.com/neka-nat/cupoch/releases/download/v0.2.2/cupoch-fat-source.zip
