### ISSUE TITLE
CreateToPointCloud2Msg ouputting wrong error

### ISSUE THREAD

**Issue by tepsaj** [neka-nat/cupoch#74]
Hi @neka-nat,

I would like to report bug in the function `CreateToPointCloud2Msg`. The error is related to the width and step sizes of the point cloud of which the PointCloud2MsgInfo is to be created.

The code has IF-statement checking that the width, point step, and row step should be over 0. At the moment the error is printed everytime the variables are over 0 and not vice versa, like it was inteded.

https://github.com/neka-nat/cupoch/blob/1c971b132b873458ba2277b93de0e77fa000efd2/src/cupoch/io/ros/pointcloud_msg.cu#L141-L143

The IF-statements should reversed so that the error is printed if the variables are under 0, like this
```c++
if (info.width_ < 0 && info.point_step_ < 0 && info.row_step_ < 0) {
    utility::LogError("[CreateToPointCloud2Msg] Width and Step sizes must be greater than 0.");
    return;
}
```
Sorry, that I didn't do pull request from this but I'm using the pip package so this was easier.

-tepsaj

**Comment by neka-nat** [comment]
Thanks!
I fixed if.
