### ISSUE TITLE
fatal: clone of 'https://gitlab.com/libeigen/eigen.git' into submodule path '/home/username/libraries/cupoch/third_party/eigen' failed

### ISSUE THREAD

**Issue by dHofmeister** [neka-nat/cupoch#81]
Dear Neka-nat, 

It seems that building from source is broken since the link to eigen's library is broken? 
https://gitlab.com/libeigen/eigen.git

( https://github.com/neka-nat/cupoch/tree/master/third_party )

Greetings

Deniz

**Comment by neka-nat** [comment]
https://gitlab.com/libeigen/eigen/-/issues/2336

**Comment by neka-nat** [comment]
It's back.
https://gitlab.com/libeigen/eigen
