### ISSUE TITLE
Pointcloud example fails

### ISSUE THREAD

**Issue by jediofgever** [neka-nat/cupoch#84]
Hi,
Sorry to bother, I met issue while testing pointcloud example which basically estimates the normals and visualizes. The first issue is, the removeNonePoints, wipes out all the points leaving no points in the cluoud hence it fails. So I disable the removeNonePoints, by setting it to false in function signature. 

The second issue I meet is, attached in the picture. 

![882023C3-15A2-4351-8D33-D3E9002F6B85](https://user-images.githubusercontent.com/18460336/136844458-c81c562e-b4e5-4738-a27c-bd064ff020d9.jpeg)

The cloud is relatively large including close to 2 ml points, but I am not sure if that the reason for this error, have tested that example ?

**Comment by jediofgever** [comment]
Thank you @neka-nat. Indeed, my GPU is quite outdated so changed it to 50 from 52 which is the default.

**Comment by neka-nat** [comment]
Hi,
Pressing the n key in the visualizer will draw the normals.
