### ISSUE TITLE
DBSCAN slow than cpu method

### ISSUE THREAD

**Issue by Xuechun-Hu** [neka-nat/cupoch#85]
Test using a small point cloud with 15million points, and it takes extremely long to process.
The gpu is nvidia a600 with 48gb memory. Cuda version is 11.2.
Is cuml used in the library? It suffers the batch shrinking problem

[2021-10-12 12:00:22.331] [debug] Read geometry::PointCloud: 15636915 vertices.

[2021-10-12 12:00:22.340] [debug] [RemoveNoneFinitePoints] 15636915 nan points have been removed.
(15636915, 3)
(15636915, 3)
block_0 has 15636915 points
| ID | GPU | MEM |
------------------
|  0 | 18% |  2% |
[2021-10-12 12:00:22.798] [debug] Precompute Neighbours
Precompute Neighbours[================>                       ] 40%

**Comment by neka-nat** [comment]
Hi,
Thank you for the reporting!
Can you share the code and data for this experiment?

**Comment by neka-nat** [comment]
Thank you for sharing the code!
Can I also share "block_0.ply" pointcloud data?

**Comment by Xuechun-Hu** [comment]
https://drive.google.com/drive/folders/1FXQ9zT3uqEblHsw5xaC-w_KyUaczEAI4?usp=sharing
there are two pointcloud files ,block_0 is the relatively smaller one

**Comment by neka-nat** [comment]
↑Can you give me access to Google Drive?
