### ISSUE TITLE
The result of using DBSCAN is wrong.

### ISSUE THREAD

**Issue by yeyang1021** [neka-nat/cupoch#93]
The result is different.
When compared with the result from "sklearn.cluster import DBSCAN"

**Comment by neka-nat** [comment]
It uses the dbscan algorithm for gpu, so the results may differ from scikitlearn's results.
[G-DBSCAN: A GPU Accelerated Algorithm for Density-based Clustering](https://www.sciencedirect.com/science/article/pii/S1877050913003438)
Some parameters are also different from those of scikitlearn, and it may be possible to adjust these to bring the results closer.
https://github.com/neka-nat/cupoch/blob/master/src/python/cupoch_pybind/geometry/pointcloud.cpp#L228
