### ISSUE TITLE
ICP algorithm have CUDA version? 

### ISSUE THREAD

**Issue by xiaopeige** [neka-nat/cupoch#95]
I found that the ICP algorithm is not GPU accelerated. Does the ICP algorithm have a CUDA version?

**Comment by neka-nat** [comment]
> I found that the ICP algorithm is not GPU accelerated. 

What does this mean?
All registration algorithms implemented in this library use CUDA.

**Comment by xiaopeige** [comment]
Use ICP to find that it takes 10ms to construct 10,000 points of kdtree. I think this is relatively slow. Is there any way to improve it?

**Comment by neka-nat** [comment]
You may need more points than that to benefit from the GPU.
The benchmark is tested with 1 million points, in which case it is about 100 times faster than the CPU.
https://raw.githubusercontent.com/neka-nat/cupoch/master/docs/_static/speedup.png
